apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-service
  labels:
    app: bmi-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bmi-service
  template:
    metadata:
      labels:
        app: bmi-service
    spec:
      nodeSelector:
        karpenter.sh/nodepool: default
      containers:
      - name: bmi-service
        image: devlopesbernardo/bmi-calculator-bmi-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: IMAGE_VERSION
          value: "latest"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bmi-service
spec:
  selector:
    app: bmi-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
