apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - services.yaml
  - servicemonitors.yaml
  - rollout.yaml
  - rollout-with-metrics.yaml

commonLabels:
  project: demo-apps
