apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-canary
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: demo-app-canary
  endpoints:
  - port: metrics
    interval: 15s
    scrapeTimeout: 10s
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-canary-metrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: demo-app-canary-metrics
  endpoints:
  - port: metrics
    interval: 15s
    scrapeTimeout: 10s
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
