apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - services.yaml
  - servicemonitors.yaml
  - blue-green-rollout.yaml
  - canary-rollout.yaml
  - canary-with-metrics-rollout.yaml

commonLabels:
  project: demo-apps
