apiVersion: v1
kind: Service
metadata:
  name: demo-app-blue-green-active
  labels:
    app: demo-app-blue-green
    type: active
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    app: demo-app-blue-green
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-blue-green-preview
  labels:
    app: demo-app-blue-green
    type: preview
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    app: demo-app-blue-green
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-canary
  labels:
    app: demo-app-canary
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    app: demo-app-canary
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-canary-canary
  labels:
    app: demo-app-canary
    type: canary
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: demo-app-canary
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-canary-stable
  labels:
    app: demo-app-canary
    type: stable
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: demo-app-canary
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-canary-metrics
  labels:
    app: demo-app-canary-metrics
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    app: demo-app-canary-metrics
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-canary-metrics-canary
  labels:
    app: demo-app-canary-metrics
    type: canary
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: demo-app-canary-metrics
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-canary-metrics-stable
  labels:
    app: demo-app-canary-metrics
    type: stable
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: demo-app-canary-metrics
