apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - configmap.yaml
  - deployment.yaml
  - job-load-test.yaml
  - cronjob.yaml

commonLabels:
  app: traffic-generator
