apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gateway/deployment.yaml
- bmi-service/deployment.yaml
- health-service/deployment.yaml
- shared/namespace.yaml

namespace: bmi-calculator

commonLabels:
  app.kubernetes.io/name: bmi-calculator
  app.kubernetes.io/version: "1.0.0"