apiVersion: v1
kind: Service
metadata:
  name: demo-app-blue-green-active
  labels:
    app: demo-app-blue-green
    type: active
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    app: demo-app-blue-green
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-blue-green-preview
  labels:
    app: demo-app-blue-green
    type: preview
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    app: demo-app-blue-green
