apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bmi-calculator

resources:
  - ../../gateway/deployment.yaml
  - ../../bmi-service/deployment.yaml
  - ../../health-service/deployment.yaml
  - ../../shared/namespace.yaml
  - ingress.yaml
